import { AttributeType } from './attribute';
import { AttributeTypeBoolean } from './boolean';
import { AttributeTypeFloat } from './float';
import { AttributeTypeFlaggedInt } from './flagged-int';
import { AttributeTypeString } from './string';
import { AttributeTypeByte } from './byte';
import { AttributeTypeInt } from './int';
import { AttributeTypeQWord } from './qword';
import { AttributeTypeUniqueId } from './unique-id';
import { AttributeTypeReservation } from './reservation';
import { AttributeTypeFlaggedByte } from './flagged-byte';
import { AttributeTypePlayerHistoryKey } from './player-history-key';
import { AttributeTypeInt64 } from './int64';
import { AttributeTypeGameMode } from './game-mode';
import { AttributeTypeAppliedDamage } from './applied-damage';
import { AttributeTypeExplosion } from './explosion';
import { AttributeTypeExtendedExplosion } from './extended-explosion';
import { AttributeTypeDamageState } from './damage-state';
import { AttributeTypeCamSettings } from './camera-settings';
import { AttributeTypeClubColors } from './club-colors';
import { AttributeTypeDemolish } from './demolish';
import { AttributeTypeTeamPaint } from './team-paint';
import { AttributeTypeLocation } from './location';
import { AttributeTypeMusicStinger } from './music-stinger';
import { AttributeTypeStatEvent } from './stat-event';
import { AttributeTypePrivateMatchSettings } from './private-match-settings';
import { AttributeTypeLoadout } from './loadout';
import { AttributeTypeLoadoutOnline } from './loadout-online';
import { AttributeTypeLoadouts } from './loadouts';
import { AttributeTypeLoadoutsOnline } from './loadouts-online';
import { AttributeTypePartyLeader } from './party-leader';
import { AttributeTypeTitle } from './title';

export const RAW_ATTRIBUTE_TYPES: { [name: string]: AttributeType } = {
  'Engine.Actor:bBlockActors': AttributeTypeBoolean,
  'Engine.Actor:bCollideActors': AttributeTypeBoolean,
  'Engine.Actor:bHidden': AttributeTypeBoolean,
  'Engine.Actor:DrawScale': AttributeTypeFloat,
  'Engine.Actor:RemoteRole': AttributeTypeEnum,
  'Engine.Actor:Role': AttributeTypeEnum,
  'Engine.GameReplicationInfo:bMatchIsOver': AttributeTypeBoolean,
  'Engine.GameReplicationInfo:GameClass': AttributeTypeFlaggedInt,
  'Engine.GameReplicationInfo:ServerName': AttributeTypeString,
  'Engine.Pawn:PlayerReplicationInfo': AttributeTypeFlaggedInt,
  'Engine.PlayerReplicationInfo:bBot': AttributeTypeBoolean,
  'Engine.PlayerReplicationInfo:bIsSpectator': AttributeTypeBoolean,
  'Engine.PlayerReplicationInfo:bReadyToPlay': AttributeTypeBoolean,
  'Engine.PlayerReplicationInfo:bTimedOut': AttributeTypeBoolean,
  'Engine.PlayerReplicationInfo:bWaitingPlayer': AttributeTypeBoolean,
  'Engine.PlayerReplicationInfo:Ping': AttributeTypeByte,
  'Engine.PlayerReplicationInfo:PlayerID': AttributeTypeInt,
  'Engine.PlayerReplicationInfo:PlayerName': AttributeTypeString,
  'Engine.PlayerReplicationInfo:RemoteUserData': AttributeTypeString,
  'Engine.PlayerReplicationInfo:Score': AttributeTypeInt,
  'Engine.PlayerReplicationInfo:Team': AttributeTypeFlaggedInt,
  'Engine.PlayerReplicationInfo:UniqueId': AttributeTypeUniqueId,
  'Engine.TeamInfo:Score': AttributeTypeInt,
  'ProjectX.GRI_X:bGameStarted': AttributeTypeBoolean,
  'ProjectX.GRI_X:GameServerID': AttributeTypeQWord,
  'ProjectX.GRI_X:MatchGUID': AttributeTypeString,
  'ProjectX.GRI_X:ReplicatedGameMutatorIndex': AttributeTypeInt,
  'ProjectX.GRI_X:ReplicatedGamePlaylist': AttributeTypeInt,
  'ProjectX.GRI_X:Reservations': AttributeTypeReservation,
  'TAGame.Ball_Breakout_TA:AppliedDamage': AttributeTypeAppliedDamage,
  'TAGame.Ball_Breakout_TA:DamageIndex': AttributeTypeInt,
  'TAGame.Ball_Breakout_TA:LastTeamTouch': AttributeTypeByte,
  'TAGame.Ball_TA:GameEvent': AttributeTypeFlaggedInt,
  'TAGame.Ball_TA:HitTeamNum': AttributeTypeByte,
  'TAGame.Ball_TA:ReplicatedAddedCarBounceScale': AttributeTypeFloat,
  'TAGame.Ball_TA:ReplicatedBallMaxLinearSpeedScale': AttributeTypeFloat,
  'TAGame.Ball_TA:ReplicatedBallScale': AttributeTypeFloat,
  'TAGame.Ball_TA:ReplicatedExplosionData': AttributeTypeExplosion,
  'TAGame.Ball_TA:ReplicatedExplosionDataExtended': AttributeTypeExtendedExplosion,
  'TAGame.Ball_TA:ReplicatedPhysMatOverride': AttributeTypeFlaggedInt,
  'TAGame.Ball_TA:ReplicatedWorldBounceScale': AttributeTypeFloat,
  'TAGame.BreakOutActor_Platform_TA:DamageState': AttributeTypeDamageState,
  'TAGame.CameraSettingsActor_TA:bUsingBehindView': AttributeTypeBoolean,
  'TAGame.CameraSettingsActor_TA:bMouseCameraToggleEnabled': AttributeTypeBoolean,
  'TAGame.CameraSettingsActor_TA:bUsingSecondaryCamera': AttributeTypeBoolean,
  'TAGame.CameraSettingsActor_TA:bUsingSwivel': AttributeTypeBoolean,
  'TAGame.CameraSettingsActor_TA:CameraPitch': AttributeTypeByte,
  'TAGame.CameraSettingsActor_TA:CameraYaw': AttributeTypeByte,
  'TAGame.CameraSettingsActor_TA:PRI': AttributeTypeFlaggedInt,
  'TAGame.CameraSettingsActor_TA:ProfileSettings': AttributeTypeCamSettings,
  'TAGame.Car_TA:AddedBallForceMultiplier': AttributeTypeFloat,
  'TAGame.Car_TA:AddedCarForceMultiplier': AttributeTypeFloat,
  'TAGame.Car_TA:AttachedPickup': AttributeTypeFlaggedInt,
  'TAGame.Car_TA:ClubColors': AttributeTypeClubColors,
  'TAGame.Car_TA:ReplicatedDemolish': AttributeTypeDemolish,
  'TAGame.Car_TA:TeamPaint': AttributeTypeTeamPaint,
  'TAGame.CarComponent_Boost_TA:bNoBoost': AttributeTypeBoolean,
  'TAGame.CarComponent_Boost_TA:BoostModifier': AttributeTypeFloat,
  'TAGame.CarComponent_Boost_TA:bUnlimitedBoost': AttributeTypeBoolean,
  'TAGame.CarComponent_Boost_TA:RechargeDelay': AttributeTypeFloat,
  'TAGame.CarComponent_Boost_TA:RechargeRate': AttributeTypeFloat,
  'TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount': AttributeTypeByte,
  'TAGame.CarComponent_Boost_TA:UnlimitedBoostRefCount': AttributeTypeInt,
  'TAGame.CarComponent_Dodge_TA:DodgeTorque': AttributeTypeLocation,
  'TAGame.CarComponent_FlipCar_TA:bFlipRight': AttributeTypeBoolean,
  'TAGame.CarComponent_FlipCar_TA:FlipCarTime': AttributeTypeFloat,
  'TAGame.CarComponent_TA:ReplicatedActive': AttributeTypeByte,
  'TAGame.CarComponent_TA:ReplicatedActivityTime': AttributeTypeFloat,
  'TAGame.CarComponent_TA:Vehicle': AttributeTypeFlaggedInt,
  'TAGame.CrowdActor_TA:GameEvent': AttributeTypeFlaggedInt,
  'TAGame.CrowdActor_TA:ModifiedNoise': AttributeTypeFloat,
  'TAGame.CrowdActor_TA:ReplicatedCountDownNumber': AttributeTypeInt,
  'TAGame.CrowdActor_TA:ReplicatedOneShotSound': AttributeTypeFlaggedInt,
  'TAGame.CrowdActor_TA:ReplicatedRoundCountDownNumber': AttributeTypeInt,
  'TAGame.CrowdManager_TA:GameEvent': AttributeTypeFlaggedInt,
  'TAGame.CrowdManager_TA:ReplicatedGlobalOneShotSound': AttributeTypeFlaggedInt,
  'TAGame.GameEvent_Soccar_TA:bBallHasBeenHit': AttributeTypeBoolean,
  'TAGame.GameEvent_Soccar_TA:bClubMatch': AttributeTypeBoolean,
  'TAGame.GameEvent_Soccar_TA:bOverTime': AttributeTypeBoolean,
  'TAGame.GameEvent_Soccar_TA:bUnlimitedTime': AttributeTypeBoolean,
  'TAGame.GameEvent_Soccar_TA:GameTime': AttributeTypeInt,
  'TAGame.GameEvent_Soccar_TA:ReplicatedMusicStinger': AttributeTypeMusicStinger,
  'TAGame.GameEvent_Soccar_TA:ReplicatedScoredOnTeam': AttributeTypeByte,
  'TAGame.GameEvent_Soccar_TA:ReplicatedServerPerformanceState': AttributeTypeByte,
  'TAGame.GameEvent_Soccar_TA:ReplicatedStatEvent': AttributeTypeStatEvent,
  'TAGame.GameEvent_Soccar_TA:RoundNum': AttributeTypeInt,
  'TAGame.GameEvent_Soccar_TA:SecondsRemaining': AttributeTypeInt,
  'TAGame.GameEvent_Soccar_TA:SeriesLength': AttributeTypeInt,
  'TAGame.GameEvent_Soccar_TA:SubRulesArchetype': AttributeTypeFlaggedInt,
  'TAGame.GameEvent_SoccarPrivate_TA:MatchSettings': AttributeTypePrivateMatchSettings,
  'TAGame.GameEvent_TA:bCanVoteToForfeit': AttributeTypeBoolean,
  'TAGame.GameEvent_TA:bHasLeaveMatchPenalty': AttributeTypeBoolean,
  'TAGame.GameEvent_TA:BotSkill': AttributeTypeInt,
  'TAGame.GameEvent_TA:GameMode': AttributeTypeGameMode,
  'TAGame.GameEvent_TA:MatchTypeClass': AttributeTypeFlaggedInt,
  'TAGame.GameEvent_TA:ReplicatedGameStateTimeRemaining': AttributeTypeInt,
  'TAGame.GameEvent_TA:ReplicatedRoundCountDownNumber': AttributeTypeInt,
  'TAGame.GameEvent_TA:ReplicatedStateIndex': AttributeTypeByte,
  'TAGame.GameEvent_TA:ReplicatedStateName': AttributeTypeInt,
  'TAGame.GameEvent_Team_TA:bForfeit': AttributeTypeBoolean,
  'TAGame.GameEvent_Team_TA:MaxTeamSize': AttributeTypeInt,
  'TAGame.GRI_TA:NewDedicatedServerIP': AttributeTypeString,
  'TAGame.PRI_TA:bIsInSplitScreen': AttributeTypeBoolean,
  'TAGame.PRI_TA:bMatchMVP': AttributeTypeBoolean,
  'TAGame.PRI_TA:bOnlineLoadoutSet': AttributeTypeBoolean,
  'TAGame.PRI_TA:bOnlineLoadoutsSet': AttributeTypeBoolean,
  'TAGame.PRI_TA:BotProductName': AttributeTypeInt,
  'TAGame.PRI_TA:bReady': AttributeTypeBoolean,
  'TAGame.PRI_TA:bUsingBehindView': AttributeTypeBoolean,
  'TAGame.PRI_TA:bUsingItems': AttributeTypeBoolean,
  'TAGame.PRI_TA:bUsingSecondaryCamera': AttributeTypeBoolean,
  'TAGame.PRI_TA:CameraPitch': AttributeTypeByte,
  'TAGame.PRI_TA:CameraSettings': AttributeTypeCamSettings,
  'TAGame.PRI_TA:CameraYaw': AttributeTypeByte,
  'TAGame.PRI_TA:ClientLoadout': AttributeTypeLoadout,
  'TAGame.PRI_TA:ClientLoadoutOnline': AttributeTypeLoadoutOnline,
  'TAGame.PRI_TA:ClientLoadouts': AttributeTypeLoadouts,
  'TAGame.PRI_TA:ClientLoadoutsOnline': AttributeTypeLoadoutsOnline,
  'TAGame.PRI_TA:ClubID': AttributeTypeInt64,
  'TAGame.PRI_TA:MatchAssists': AttributeTypeInt,
  'TAGame.PRI_TA:MatchBreakoutDamage': AttributeTypeInt,
  'TAGame.PRI_TA:MatchGoals': AttributeTypeInt,
  'TAGame.PRI_TA:MatchSaves': AttributeTypeInt,
  'TAGame.PRI_TA:MatchScore': AttributeTypeInt,
  'TAGame.PRI_TA:MatchShots': AttributeTypeInt,
  'TAGame.PRI_TA:MaxTimeTillItem': AttributeTypeInt,
  'TAGame.PRI_TA:PartyLeader': AttributeTypePartyLeader,
  'TAGame.PRI_TA:PawnType': AttributeTypeByte,
  'TAGame.PRI_TA:PersistentCamera': AttributeTypeFlaggedInt,
  'TAGame.PRI_TA:PlayerHistoryKey': AttributeTypePlayerHistoryKey,
  'TAGame.PRI_TA:PlayerHistoryValid': AttributeTypeBoolean,
  'TAGame.PRI_TA:ReplicatedGameEvent': AttributeTypeFlaggedInt,
  'TAGame.PRI_TA:ReplicatedWorstNetQualityBeyondLatency': AttributeTypeByte,
  'TAGame.PRI_TA:SteeringSensitivity': AttributeTypeFloat,
  'TAGame.PRI_TA:SkillTier': AttributeTypeFlaggedByte,
  'TAGame.PRI_TA:TimeTillItem': AttributeTypeInt,
  'TAGame.PRI_TA:Title': AttributeTypeInt,
  'TAGame.PRI_TA:TotalXP': AttributeTypeInt,
  'TAGame.PRI_TA:PrimaryTitle': AttributeTypeTitle,
  'TAGame.PRI_TA:SecondaryTitle': AttributeTypeTitle,
  'TAGame.PRI_TA:SpectatorShortcut': AttributeTypeInt,
  'TAGame.RBActor_TA:bFrozen': AttributeTypeBoolean,
  'TAGame.RBActor_TA:bIgnoreSyncing': AttributeTypeBoolean,
  'TAGame.RBActor_TA:bReplayActor': AttributeTypeBoolean,
  'TAGame.RBActor_TA:ReplicatedRBState': AttributeTypeRigidBodyState,
  'TAGame.RBActor_TA:WeldedInfo': AttributeTypeWeldedInfo,
  'TAGame.SpecialPickup_BallFreeze_TA:RepOrigSpeed': AttributeTypeFloat,
  'TAGame.SpecialPickup_BallVelcro_TA:AttachTime': AttributeTypeFloat,
  'TAGame.SpecialPickup_BallVelcro_TA:bBroken': AttributeTypeBoolean,
  'TAGame.SpecialPickup_BallVelcro_TA:bHit': AttributeTypeBoolean,
  'TAGame.SpecialPickup_BallVelcro_TA:BreakTime': AttributeTypeFloat,
  'TAGame.SpecialPickup_Targeted_TA:Targeted': AttributeTypeFlaggedInt,
  'TAGame.Team_Soccar_TA:GameScore': AttributeTypeInt,
  'TAGame.Team_TA:ClubColors': AttributeTypeClubColors,
  'TAGame.Team_TA:ClubID': AttributeTypeInt64,
  'TAGame.Team_TA:CustomTeamName': AttributeTypeString,
  'TAGame.Team_TA:GameEvent': AttributeTypeFlaggedInt,
  'TAGame.Team_TA:LogoData': AttributeTypeFlaggedInt,
  'TAGame.Vehicle_TA:bDriving': AttributeTypeBoolean,
  'TAGame.Vehicle_TA:bReplicatedHandbrake': AttributeTypeBoolean,
  'TAGame.Vehicle_TA:ReplicatedSteer': AttributeTypeByte,
  'TAGame.Vehicle_TA:ReplicatedThrottle': AttributeTypeByte,
  'TAGame.VehiclePickup_TA:bNoPickup': AttributeTypeBoolean,
  'TAGame.VehiclePickup_TA:ReplicatedPickupData': AttributeTypePickup,
  'TAGame.VehiclePickup_TA:NewReplicatedPickupData': AttributeTypePickupNew,
  'TAGame.Ball_Haunted_TA:LastTeamTouch': AttributeTypeByte,
  'TAGame.Ball_Haunted_TA:TotalActiveBeams': AttributeTypeByte,
  'TAGame.Ball_Haunted_TA:DeactivatedGoalIndex': AttributeTypeByte,
  'TAGame.Ball_Haunted_TA:ReplicatedBeamBrokenValue': AttributeTypeByte,
  'TAGame.Ball_Haunted_TA:bIsBallBeamed': AttributeTypeBoolean,
  'TAGame.SpecialPickup_Rugby_TA:bBallWelded': AttributeTypeBoolean
};
